schema_registry_listener_port: 8081

broker:
  config:
    port: 9092

schema:
  registry:
    user: cp-schema-registry
    group: confluent
    config_file: /etc/schema-registry/schema-registry.properties
    service_name: confluent-schema-registry
    systemd_override: /etc/systemd/system/confluent-schema-registry.service.d
    config:
      listeners: http://0.0.0.0:{{schema_registry_listener_port}}
      kafkastore.topic: _schemas
      debug: false
      kafkastore.ssl.endpoint.identification.algorithm: ""
      kafkastore.topic.replication.factor: 1
      config.storage.replication.factor: 1
      offset.storage.replication.factor: 1
      status.storage.replication.factor: 1
    environment:
      SCHEMA_REGISTRY_HEAP_OPTS: "-Xmx256M -Dkafka.logs.dir=/var/log/kafka-schema"
    systemd:
      enabled: yes
      state: started
