all:
  vars:
    ansible_connection: ssh
    ansible_ssh_user: fedora
    ansible_become: true
    security_mode: sasl_ssl
sandbox:
  hosts:
    5.196.71.146:
      kafka:
        broker:
          id: 1